# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_picture',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
