# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170524_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='first_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fourth_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='second_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='third_answer',
            field=models.CharField(max_length=100),
        ),
    ]
