# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170525_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='first_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fourth_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='second_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='third_answer',
            field=models.TextField(),
        ),
    ]
