# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170525_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.TextField(),
        ),
    ]
